apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-pac-bbmy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-pac-bbmy
    app.kubernetes.io/part-of: build-suite-test-application-vccj
  name: test-component-pac-bbmy
  namespace: build-e2e-ysip-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-component-pac-bbmy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test-component-pac-bbmy
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images@sha256:e1fd87d52bb95968268957da20365ea35be49817e81f262f5ad48f2f57bd93dc
        imagePullPolicy: Always
        name: container-image
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
